# Generated by Django 5.0.6 on 2024-08-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('mrp', models.IntegerField()),
                ('last_7_day_sale', models.IntegerField()),
                ('fit', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('neck', models.CharField(max_length=100)),
                ('sleeve', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('available_skus', models.ManyToManyField(to='ignis.sku')),
            ],
        ),
    ]
